name: simple_locale
description: "A package for easily getting and switching locale information. It is designed to coexist with Flutter's standard multilingual methods."
version: 1.0.1
repository: https://github.com/MasahideMori-SimpleAppli/simple_locale

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_localizations:
    sdk: flutter
